-- create SEQUENCE MESSAGE_seq as bigint start with 1 increment by 1
-- alter table MESSAGE_TOKEN ADD CONSTRAINT MESSAGE_FK FOREIGN KEY (MESSAGE_ID) REFERENCES MESSAGE (MESSAGE_ID)
-- alter table MESSAGE_TOKEN ADD CONSTRAINT TOKEN_FK FOREIGN KEY (TOKEN) REFERENCES TOKEN (TOKEN)
-- create UNIQUE INDEX MESSAGE_TOKEN_IDX ON MESSAGE_TOKEN (MESSAGE_ID ASC, TOKEN ASC)
-- create INDEX MESSAGE_IDX ON MESSAGE_TOKEN (MESSAGE_ID ASC)
-- create DATABASE confluence CHARACTER SET utf8 COLLATE utf8_bin;
-- ENGINE=INNODB DEFAULT CHARSET=utf8;

/*delete from MESSAGE_TOKEN;
delete from TOKEN;
delete from MESSAGE*/;

--SET AUTOCOMMIT = 0;

drop table IF EXISTS MESSAGE_TOKEN CASCADE;
drop table IF EXISTS TOKEN CASCADE;
drop table IF EXISTS MESSAGE CASCADE;

create table MESSAGE (
MESSAGE_ID VARCHAR(255) NOT NULL,
SUBJECT VARCHAR(255),
IS_SPAM BOOLEAN NOT NULL,
RECEIVED_DATE TIMESTAMP NOT NULL,
SENDER VARCHAR(100)
)ENGINE=InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

COMMENT ON TABLE MESSAGE IS 'Einzelne Mails';
COMMENT ON COLUMN MESSAGE.IS_SPAM IS 'SPAM oder HAM';

alter table MESSAGE add constraint MESSAGE_PK PRIMARY KEY (MESSAGE_ID);
alter table MESSAGE add constraint MESSAGE_CHK CHECK (LENGTH(TRIM(MESSAGE_ID)) > 0);

create table TOKEN (
TOKEN VARCHAR(50) NOT NULL,
HAM_COUNT INTEGER NOT NULL,
SPAM_COUNT INTEGER NOT NULL
)ENGINE=InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

COMMENT ON TABLE TOKEN IS 'Tabelle aller vorhandenen Token';
COMMENT ON COLUMN TOKEN.HAM_COUNT IS 'Anzahl Vorkommen in HAM-Mails';
COMMENT ON COLUMN TOKEN.SPAM_COUNT IS 'Anzahl Vorkommen in SPAM-Mails';

alter table TOKEN add constraint TOKEN_PK PRIMARY KEY (TOKEN);
alter table TOKEN add constraint TOKEN_TOKEN_CHK CHECK (LENGTH(TRIM(TOKEN)) > 0);
alter table TOKEN add constraint TOKEN_HAM_CHK CHECK (HAM_COUNT >= 0);
alter table TOKEN add constraint TOKEN_SPAM_CHK CHECK (SPAM_COUNT >= 0);

create table MESSAGE_TOKEN (
MESSAGE_ID VARCHAR(255) NOT NULL,
TOKEN VARCHAR(50) NOT NULL,
COUNT INTEGER NOT NULL
)ENGINE=InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

COMMENT ON TABLE MESSAGE_TOKEN IS 'Zu einer Mail gehörende Token';
COMMENT ON COLUMN MESSAGE_TOKEN.COUNT IS 'Häufigkeit des Tokens in der Mail';

alter table MESSAGE_TOKEN add constraint MT_MESSAGE_ID_FK FOREIGN KEY (MESSAGE_ID) REFERENCES MESSAGE (MESSAGE_ID);
alter table MESSAGE_TOKEN add constraint MT_TOKEN_FK FOREIGN KEY (TOKEN) REFERENCES TOKEN (TOKEN);
alter table MESSAGE_TOKEN add constraint MT_MESSAGETOKEN_UQ UNIQUE KEY (MESSAGE_ID, TOKEN);
alter table MESSAGE_TOKEN add INDEX MT_MESSAGE_KEY (MESSAGE_ID);
-- create index MT_MESSAGE_KEY on MESSAGE_TOKEN (MESSAGE_ID);
-- TOKEN <> ''
alter table MESSAGE_TOKEN add constraint MT_MESSAGE_ID_CHK CHECK (LENGTH(TRIM(MESSAGE_ID)) > 0);
alter table MESSAGE_TOKEN add constraint MT_TOKEN_CHK CHECK (LENGTH(TRIM(TOKEN)) > 0);

--commit;
