SET DATABASE SQL SYNTAX MYS TRUE
-- or the equivalent URL property sql.syntax_mys=true
-- für "INSERT INTO ... ON DUPLICATE KEY UPDATE" Syntax

drop table IF EXISTS MESSAGE_TOKEN;
drop table IF EXISTS TOKEN;
drop table IF EXISTS MESSAGE;

create table MESSAGE (
MESSAGE_ID VARCHAR(255) NOT NULL,
SUBJECT VARCHAR(255),
IS_SPAM BOOLEAN NOT NULL,
RECEIVED_DATE TIMESTAMP NOT NULL,
SENDER VARCHAR(100)
);

COMMENT ON TABLE MESSAGE IS 'Einzelne Mails';
COMMENT ON COLUMN MESSAGE.IS_SPAM IS 'SPAM oder HAM';

alter table MESSAGE add constraint MESSAGE_PK PRIMARY KEY (MESSAGE_ID);
alter table MESSAGE add constraint MESSAGE_CHK CHECK (LENGTH(TRIM(MESSAGE_ID)) > 0);

create table TOKEN (
TOKEN VARCHAR(50) NOT NULL,
HAM_COUNT INTEGER NOT NULL,
SPAM_COUNT INTEGER NOT NULL
);

COMMENT ON TABLE TOKEN IS 'Tabelle aller vorhandenen Token';
COMMENT ON COLUMN TOKEN.HAM_COUNT IS 'Anzahl Vorkommen in HAM-Mails';
COMMENT ON COLUMN TOKEN.SPAM_COUNT IS 'Anzahl Vorkommen in SPAM-Mails';

alter table TOKEN add constraint TOKEN_PK PRIMARY KEY (TOKEN);
alter table TOKEN add constraint TOKEN_TOKEN_CHK CHECK (LENGTH(TRIM(TOKEN)) > 0);
alter table TOKEN add constraint TOKEN_HAM_CHK CHECK (HAM_COUNT >= 0);
alter table TOKEN add constraint TOKEN_SPAM_CHK CHECK (SPAM_COUNT >= 0);

create table MESSAGE_TOKEN (
MESSAGE_ID VARCHAR(255) NOT NULL,
TOKEN VARCHAR(50) NOT NULL,
COUNT INTEGER NOT NULL
);

COMMENT ON TABLE MESSAGE_TOKEN IS 'Zu einer Mail gehörende Token';
COMMENT ON COLUMN MESSAGE_TOKEN.COUNT IS 'Häufigkeit des Tokens in der Mail';

alter table MESSAGE_TOKEN add constraint MT_MESSAGE_ID_FK FOREIGN KEY (MESSAGE_ID) REFERENCES MESSAGE (MESSAGE_ID);
alter table MESSAGE_TOKEN add constraint MT_TOKEN_FK FOREIGN KEY (TOKEN) REFERENCES TOKEN (TOKEN);
alter table MESSAGE_TOKEN add constraint MT_MESSAGETOKEN_UQ UNIQUE (MESSAGE_ID, TOKEN);
create index MT_MESSAGE_KEY on MESSAGE_TOKEN (MESSAGE_ID);
-- TOKEN <> ''
alter table MESSAGE_TOKEN add constraint MT_MESSAGE_ID_CHK CHECK (LENGTH(TRIM(MESSAGE_ID)) > 0);
alter table MESSAGE_TOKEN add constraint MT_TOKEN_CHK CHECK (LENGTH(TRIM(TOKEN)) > 0);

